#!/bin/bash

tfile=$(mktemp /tmp/build-prog-XXXXXX.jpg)
gip=$(parse_ip ~/Dropbox/Apps/upload_ip/geryon’s\ ip.html)
ssh ${gip} curl "http://clota:8080/?action=snapshot" | cat  >${tfile}
sxiv ${tfile}
rm ${tfile}
