#! /usr/bin/env python
# -*- coding: utf-8 ; mode: python -*-
# © Copyright 2010–13 Roland Sieker <ospalh@gmail.com>
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import os
import time


__version__ = '1.1.1'


def age_seconds(file):
    """Return the age of a file in seconds."""
    #return int(time.time() - os.stat(file).st_ctime)
    return time.time() - os.stat(file).st_mtime


if __name__ == '__main__':
    import sys
    helpmsg = """Usage: age FILE [FILE2 ... [FILE_N]]
Prints the age of FILE in seconds
"""

    if len(sys.argv) < 2:
        print helpmsg
        sys.exit(0)
    if len(sys.argv) == 2:
        try:
            print(int(age_seconds(sys.argv[1])))
        except OSError as ose:
            sys.stderr.write(str(ose) + '\n')
    if len(sys.argv) > 2:
        for fl in sys.argv[1:]:
            flu = unicode(fl, sys.getfilesystemencoding())
            try:
                print(unicode.ljust(flu + u':', 20) +
                      str(int(age_seconds(fl))))
            except OSError as ose:
                sys.stderr.write(str(ose) + '\n')
