#! /usr/bin/env python
# -*- coding: utf-8 ; mode: python -*-
# © 2010–2 ospalh
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import time, os

VERSION = '1.0.1'

def print_age(file):
#    print(int(time.time() - os.stat(file).st_ctime))
    print(int(time.time() - os.stat(file).st_mtime))


if __name__ == '__main__':
    import sys, string

    helpmsg = """Usage: age FILE [FILE2 ... [FILE_N]]
Prints the age of FILE in seconds
"""

    if len(sys.argv) < 2:
        print helpmsg
        sys.exit(0)
        
    if len(sys.argv) == 2:
        print_age(sys.argv[1])

    if len(sys.argv) > 2:
        for fl in sys.argv[1:]:
            print (string.ljust(fl + ':' ,20)),
            print_age(fl)
                  


