#! /usr/bin/env python
# -*- coding: utf-8 ; mode: python -*-
# © Copyright 2010–2 ospalh@gmail.com
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import time
import os

VERSION = '1.0.2'

def print_age(file):
    """Print the age of a file."""
    #print(int(time.time() - os.stat(file).st_ctime))
    print(int(time.time() - os.stat(file).st_mtime))


if __name__ == '__main__':
    import sys
    import string

    helpmsg = """Usage: age FILE [FILE2 ... [FILE_N]]
Prints the age of FILE in seconds
"""

    if len(sys.argv) < 2:
        print helpmsg
        sys.exit(0)

    if len(sys.argv) == 2:
        try:
            print_age(sys.argv[1])
        except OSError as ose:
            sys.stderr.write(str(ose) + '\n')


    if len(sys.argv) > 2:
        for fl in sys.argv[1:]:
            print (string.ljust(fl + ':' ,20)),
            try:
                print_age(fl)
            except OSError as ose:
                print ('')
                sys.stderr.write(str(ose) + '\n')
