#!/bin/bash

#Oh, when this is a manga or othe right-to-left work, do something like `rename _0. _2. *_0.` afterwards. This is a quick hack. *shrug*
mkdir -p lr
for fl in *.*
do
    pr=$(echo ${fl} | awk  -F "." '{print $1}')
    su=$(echo ${fl} | awk  -F "." '{print $2}')
    echo $pr
    convert "${fl}" -crop 2x1@ +repage lr/${pr}_%d.${su}
done
