#!/usr/bin/env python3
# -*- coding: utf-8 ; mode: python -*-
#
#  © Copyright 2016–19 Roland Sieker <ospalh@gmail.com>
#
# License: GNU AGPL, version 3 or later;
#  http://www.gnu.org/licenses/agpl.html




import argparse
import re
import subprocess
from urllib.parse import unquote

__version__ = '0.0.1'

def do_process(playlist, target):
    with open(playlist, 'r') as inf:
        for line in inf.readlines():
            line = line.rstrip()
            if line.startswith('File'):
                mfp = re.sub(r'^File[0-9]+=', r"", line)
                mfile = unquote(mfp)
                print(mfile)
                subprocess.call(["adb", "push", mfile, target])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="""Push files from pls play list to fon with adb.""")
    parser.add_argument("--playlist", "-p", type=str, help='''The playlist''')
    parser.add_argument(
        "--target", "-t", type=str, default="/sdcard/Music/",
        help='''The target folder on the fon''')
    args = parser.parse_args()
    do_process(args.playlist, args.target)
