#!/bin/bash

INFILE="$1"
TMPOUTFILE="${INFILE%.*}"
# OUTFILE="${TMPOUTFILE##*/}.ogg"
OUTFILE="${TMPOUTFILE##*/}.mp3"
# OUTFILE="${TMPOUTFILE##*/}"


# nice ffmpeg -i "${INFILE}" -vn -acodec libvorbis "${OUTFILE}"
# nice ffmpeg -i "${INFILE}" -vn -acodec copy "${OUTFILE}"
nice ffmpeg -i "${INFILE}" -vn -acodec mp3 "${OUTFILE}"
#nice ffmpeg -i "${INFILE}" -vn -acodec copy "${TMPOUTFILE}".mp3
#nice ffmpeg -i "${INFILE}" -vn -acodec copy "${TMPOUTFILE}".aac
