#!/usr/bin/env python3
# -*- coding: utf-8 ; mode: python -*-
#
#  © Copyright 2020 Roland Sieker <ospalh@gmail.com>
#
# License: GNU AGPL, version 3 or later;
#  http://www.gnu.org/licenses/agpl.html


import shutil

start=198

for nr in range(0, 48, 2):
    try:
        shutil.move(
            'redsongs-{nr:03d}_0.ppm'.format(nr=nr),
            'redsong-{tg:03d}.ppm'.format(tg=start-2*nr))
    except FileNotFoundError:
        print('no {}'.format(nr))
