#!/bin/bash

if [ $# -gt 2 ]
then
    extension=$3
else
    extension=.doc
fi

base_name=$(basename "$1" $extension)


if [ $# -gt 1 ]
then
    dir_name="$2"
else
    dir_name="$base_name"
fi

ooffice --headless --convert-to html --outdir "$dir_name" "$1"

## The tidy messed up the encoding at least once
#pushd "$dir_name"
#tidy -config ~/.tidy_options -m "$base_name".html
#popd
